databaseChangeLog:
  - changeSet:
      id: create.table.${product}
      author: dnovysh
      dbms: postgresql
      preConditions:
        - onFail: MARK_RAN
        - not:
            tableExists:
              schemaName: ${schema}
              tableName: ${product}
      changes:
        - createTable:
            schemaName: ${schema}
            tableName: ${product}
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
                    primaryKeyName: pk_${product}_id
              - column:
                  name: company_id
                  type: UUID
                  constraints:
                    nullable: false
                    foreignKeyName: fk_${product}_${company}
                    references: ${company}(id)
              - column:
                  name: name
                  type: varchar(100)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: text
